package com.example.androidbrain.MathGame;

import android.content.Intent;
import android.os.Bundle;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.example.androidbrain.R;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.HashMap;

public class MathGameRegister extends AppCompatActivity {

    EditText etusername,etuseremail,etpassword;
    Button btnregister;

    FirebaseAuth firebaseAuth;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.math_game_register_activity);

        etusername=findViewById(R.id.etusername);
        etuseremail=findViewById(R.id.etuseremail);
        etpassword=findViewById(R.id.etpassword);
        btnregister=findViewById(R.id.btnregister);


       firebaseAuth = FirebaseAuth.getInstance();
        FirebaseDatabase database = FirebaseDatabase.getInstance();



        btnregister.setOnClickListener(view -> {

            String username = etusername.getText().toString();
            String useremail = etuseremail.getText().toString();
            String password = etpassword.getText().toString();

            // 1. Create the Firebase Auth user
            firebaseAuth.createUserWithEmailAndPassword(useremail, password)
                    .addOnCompleteListener(task -> {
                        if (task.isSuccessful()) {

                            // 2. Get the UID generated by Firebase
                            String uid = firebaseAuth.getCurrentUser().getUid();

                            // 3. Build your user object (do NOT store passwords)
                            HashMap<String, Object> user = new HashMap<>();
                            user.put("username", username);
                            user.put("email", useremail);
                            user.put("uid", uid);

                            // 4. Insert into Realtime Database under the UID
                            DatabaseReference myRef = FirebaseDatabase.getInstance()
                                    .getReference("users")
                                    .child(uid);

                            myRef.setValue(user)
                                    .addOnSuccessListener(unused -> {
                                        Toast.makeText(this, "User registered successfully!", Toast.LENGTH_SHORT).show();
                                        startActivity(new Intent(this, MathGameHome.class));
                                        finish();
                                    })
                                    .addOnFailureListener(e -> {
                                        Toast.makeText(this, "Failed to save user data", Toast.LENGTH_SHORT).show();
                                    });

                        } else {
                            Toast.makeText(this, "Auth failed: " + task.getException().getMessage(), Toast.LENGTH_LONG).show();
                        }
                    });
        });



    }



}